


export const data = [
    {
        name: 'Lemon Cherry Gelato',
        effects: ['tingly', 'relaxed', 'giggly'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-40.png?auto=compress%2Cformat&w=215&dpr=1',
    },
    {
        name: 'Blue Dream',
        effects: ['creative', 'euphoric', 'happy'],
        thc: 21,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/blue-dream.png?auto=compress%2Cformat&w=215&dpr=1',
    },
    {
        name: 'Wedding Cake',
        effects: ['relaxed', 'aroused', 'hungry'],
        thc: 24,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
       image: 'https://leafly-public.imgix.net/strains/photos/m2y50HYRBu0dHY4JSdSx_wedding-cake_jman.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Permanent Marker',
        effects: ['tingly', 'relaxed', 'euphoric'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
       image: 'https://leafly-public.imgix.net/strains/photos/aMsjhhOYQualXxE7TqQt_LEF-STOY2023-StrainPDP-1080x1080.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'GG4',
        effects: ['relaxed', 'sleepy', 'hungry'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
       image: 'https://images.leafly.com/flower-images/gg-4.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Super Boof',
        effects: ['giggly', 'euphoric', 'focused'],
        thc: 26,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
       image: 'https://leafly-public.imgix.net/strains/photos/eK2NOtifQeuwvKBNqGuV_Screenshot%202024-12-11%20at%209.22.55%20AM.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Grandaddy Purple',
        effects: ['sleepy', 'relaxed', 'hungry'],
        thc: 17,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
       image: 'https://images.leafly.com/flower-images/granddaddy-purple.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Ice Cream Cake',
        effects: ['sleepy', 'relaxed', 'hungry'],
        thc: 22,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
       image: 'https://images.leafly.com/flower-images/defaults/generic/strain-32.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Sour Diesel',
        effects: ['energetic', 'talkative', 'uplifted'],
        thc: 19,
        hasCbd: false,
        type: 'Indica',
        medical: 'Stress',
       image: 'https://leafly-public.imgix.net/strains/photos/5SPDG4T4TcSO8PgLgWHO_SourDiesel_AdobeStock_171888473.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Runtz',
        effects: ['talkative', 'relaxed', 'giggly'],
        thc: 21,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
       image: 'https://images.leafly.com/flower-images/runtz-nug-image.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Gelato',
        effects: ['relaxed', 'aroused', 'euphoric'],
        thc: 21,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/gelato.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Cereal Milk',
        effects: ['aroused', 'relaxed', 'giggly'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/fRrra4kRgiCHsreJvZDw_cereal%20milk%20nug%20small.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'White Widow',
        effects: ['euphoric', 'uplifted', 'talkative'],
        thc: 15,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/white-widow.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'OG Kush',
        effects: ['hungry', 'relaxed', 'sleepy'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/og-kush.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Girl Scout Cookies',
        effects: ['relaxed', 'hungry', 'happy'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/gsc.png?auto=compress%2Cformat&w=215&dpr=1',
        
    },
        {
        name: 'Northern Lights',
        effects: ['sleepy', 'relaxed', 'hungry'],
        thc: 18,
        hasCbd: false,
        type: 'Indica',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/northern-lights.png?auto=compress%2Cformat&w=350&dpr=1',
        
    },
        {
        name: 'Pineapple Express',
        effects: ['happy', 'giggly', 'energetic'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress & Depression',
        image: 'https://images.leafly.com/flower-images/pineapple-express.png?auto=compress%2Cformat&w=350&dpr=1',
       
    },
    {
        name: 'Biscotti',
        effects: ['tingly', 'relaxed', 'euphoric'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-29.png?auto=compress%2Cformat&w=350&dpr=1',
    },
    {
        name: 'Jack Herer',
        effects: ['focused', 'energetic', 'creative'],
        thc: 18,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress & Depression',
        image: 'https://images.leafly.com/flower-images/jack-herer.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'GMO Cookies',
        effects: ['relaxed', 'sleepy', 'euphoric'],
        thc: 28,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/red-orange-amber/strain-2.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Sherbert',
        effects: ['relaxed', 'tingly', 'happy'],
        thc: 18,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/sunset-sherbert.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Gary Payton',
        effects: ['giggly', 'relaxed', 'euphoric'],
        thc: 22,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/JNC0ZSxRVGZyjFszg0po_GaryPayton%20(1).jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Gumbo',
        effects: ['sleepy', 'relaxed', 'hungry'],
        thc: 19,
        hasCbd: false,
        type: 'Indica',
        medical: 'Pain',
        image: 'https://images.leafly.com/flower-images/defaults/purple/strain-5.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Apple Fritter',
        effects: ['tingly', 'relaxed', 'giggly'],
        thc: 24,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/ziw0L3SZSIyM6uiLup73_AppleFritter%20(1).jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Oreoz',
        effects: ['relaxed', 'hungry', 'tingly'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-40.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Durban Poison',
        effects: ['focused', 'energetic', 'uplifted'],
        thc: 19,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/durban-poison.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Pink Runtz',
        effects: ['talkative', 'tingly', 'giggly'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/short-dense-heavy/strain-15.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Purple Punch',
        effects: ['sleepy', 'relaxed', 'hungry'],
        thc: 18,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/purple-punch-fixed.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'The Original Z',
        effects: ['relaxed', 'sleepy', 'hungry'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://leafly-public.imgix.net/strains/photos/6VF5EvUTjqZPKFVOQAAY_Zkittlez.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Mac 1',
        effects: ['uplifted', 'euphoric', 'relaxed'],
        thc: 22,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/X6WMoxxxTSFF7t7tOqgO_MAC.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'RS11',
        effects: ['focused', 'giggly', 'relaxed'],
        thc: 24,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-27.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Jealousy',
        effects: ['giggly', 'relaxed', 'talkative'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/lfgn9PfQcS7RL18QA4te_Jealousy-PDP-Image-v1%20copy.jpeg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'White Runtz',
        effects: ['tingly', 'relaxed', 'euphoric'],
        thc: 18,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-9.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Dosidos',
        effects: ['relaxed', 'sleepy', 'tingly'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/jdRI25LqQM6Wavphys2K_nug-dosidos-v1.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Zoap',
        effects: ['giggly', 'relaxed', 'euphoric'],
        thc: 21,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/QEJXLkqjSWufdzJEi0PR_Deo%20Farms%20Zoap%20Photo%20by%20David%20Downs%20Leafly%202%20smaller.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Strawberry Cough',
        effects: ['uplifted', 'energetic', 'happy'],
        thc: 19,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/strawberry-cough.png?auto=compress%2Cformat&w=215&dpr=1',
    },
    {
        name: 'Gelato #41',
        effects: ['relaxed', 'aroused', 'tingly'],
        thc: 21,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/purple/strain-8.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Green Crack',
        effects: ['energetic', 'focused', 'talkative'],
        thc: 17,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/green-crack.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Mimosa',
        effects: ['focused', 'energetic', 'uplifted'],
        thc: 19,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/sE4UZNIUQbSxoqEEk0E1_Mimosa.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Amnesia Haze',
        effects: ['giggly', 'euphoric', 'talkative'],
        thc: 19,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-25.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Cherry Pie',
        effects: ['relaxed', 'giggly', 'happy'],
        thc: 16,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/cherry-pie.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Kush Mints',
        effects: ['aroused', 'relaxed', 'euphoric'],
        thc: 28,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-17.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Cap Junky',
        effects: ['giggly', 'tingly', 'relaxed'],
        thc: 19,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/YewiQ2IoTQOG9h6saIVZ_LA%20Made%20-%20Cap%20Junky%20-%20cover%20-%20David%20Downs%20at%20leafly%20copy%20smol.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Mochi',
        effects: ['sleepy', 'relaxed', 'hungry'],
        thc: 23,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/purple/strain-5.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Super Lemon Haze',
        effects: ['energetic', 'focused', 'uplifted'],
        thc: 19,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress',
        image: 'https://leafly-public.imgix.net/strains/photos/QRio3lTnO1PsVFx8Sxw1_super-lemon-haze_jman.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Maui Wowie',
        effects: ['energetic', 'uplifted', 'happy'],
        thc: 19,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-18.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Lemon Haze',
        effects: ['giggly', 'talkative', 'happy'],
        thc: 19,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/defaults/red-orange-amber/strain-4.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Rainbow Belts',
        effects: ['relaxed', 'giggly', 'euphoric'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/purple/strain-3.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'White Truffle',
        effects: ['tingly', 'aroused', 'relaxed'],
        thc: 24,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/frosty/strain-2.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Gelonade',
        effects: ['energetic', 'focused', 'talkative'],
        thc: 22,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-16.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Slurricane',
        effects: ['sleepy', 'relaxed', 'hungry'],
        thc: 21,
        hasCbd: false,
        type: 'Indica',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/MPWPStPKT0mQMfMPq3fX_Slurricane.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Chemdawg',
        effects: ['euphoric', 'relaxed', 'tingly'],
        thc: 18,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-1.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Cheetah Piss',
        effects: ['aroused', 'giggly', 'focused'],
        thc: 25,
        hasCbd: false,
         type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-10.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'AK-47',
        effects: ['hungry', 'happy', 'talkative'],
        thc: 19,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-1.png?auto=compress%2Cformat&w=350&dpr=1',
    },
]